### ISSUE TITLE
README file steps not very accurate

### ISSUE THREAD

**Issue by brunobraga95** [brunobraga95/FIFA-manager#21]
Even if someone follow those steps, the person will not be able to run gulp serve. The file needs to have more steps and consider computers that do not have neither node,npm and gulp installed.

**Comment by tiagoalvesdulce** [comment]
Is it OK now? just added the prerequisites to run the commands, if you had to do anything else to get it working, please let me know.

**Comment by fernandoabolafio** [comment]
Are you guys talking about the README in the root folder? Because that one shows pretty uncompleted. It just says: 

```
FIFA-manager
Save FIFA games results!!!!
```

If you have it better written in a different directory please replace it. Otherwise give us there some introduction to how to get the app running on localhost as the same way you are running it to test/dev right now.

**Comment by tiagoalvesdulce** [comment]
Solved
